export const blogPosts = [
    {
      id: "1",
      title: "Getting Started with Next.js",
      description: "Learn how to build modern web applications with Next.js",
      date: "April 1, 2025",
      readTime: "5 min read",
      slug: "getting-started-with-nextjs",
      category: "Development",
      image: "/placeholder.svg?height=400&width=600",
      featured: true,
    },
    {
      id: "2",
      title: "The Power of AI in Web Development",
      description: "Discover how AI is transforming the way we build websites",
      date: "April 2, 2025",
      readTime: "7 min read",
      slug: "ai-in-web-development",
      category: "Technology",
      image: "/placeholder.svg?height=400&width=600",
      featured: false,
    },
    {
      id: "3",
      title: "Responsive Design Best Practices",
      description: "Tips and tricks for creating responsive websites that work on any device",
      date: "April 3, 2025",
      readTime: "6 min read",
      slug: "responsive-design-best-practices",
      category: "Design",
      image: "/placeholder.svg?height=400&width=600",
      featured: false,
    },
    {
      id: "4",
      title: "The Future of Web Animation",
      description: "Exploring the latest trends in web animation and interactive experiences",
      date: "April 4, 2025",
      readTime: "8 min read",
      slug: "future-of-web-animation",
      category: "Design",
      image: "/placeholder.svg?height=400&width=600",
      featured: false,
    },
    {
      id: "5",
      title: "Building Accessible Web Applications",
      description: "How to ensure your web applications are accessible to everyone",
      date: "April 5, 2025",
      readTime: "9 min read",
      slug: "building-accessible-web-applications",
      category: "Development",
      image: "/placeholder.svg?height=400&width=600",
      featured: false,
    },
    {
      id: "6",
      title: "Performance Optimization Techniques",
      description: "Strategies to make your websites faster and more efficient",
      date: "April 6, 2025",
      readTime: "7 min read",
      slug: "performance-optimization-techniques",
      category: "Development",
      image: "/placeholder.svg?height=400&width=600",
      featured: false,
    },
  ]